dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: WKv16GutsCd+dEaz42OvvOdKLWHzHaLD6qU70H48HVt7imKNaXcCvRNTvmdALkvvi4CTHTCbpAK45EQkL9IDA6ThLY7D2D2t2zqIy7+BMVUU/PuK6s41HzxreGDAv9m8KXi9pNCrKK5YUtGQnsoYKNYmukcgMUrWSeMQiZBzZkm72j+g2dESUyMoZsv/ZZIGNxxdaRgWCTJz0eCIuMaVSz4qZAttAPsFinC7fS1GbEyppcWkL2hg99n4fNABP63qihiq0ndYyMiiTa00hjmf0h29jAANN1Ww8Xix3GXXVC/CbuTABIUblovDU1P9qVS/QMwstwhO7QPOJ5Ph3VTrxssLBfiMheP4m5cNcAY7vkoMfRGLtVNGumgAV+cQXSSDuHKtBnsb1QabRI7L9mwKBFcytV4fZTNGqsnKk6hue5mJi0r+rPyHjeCaH7HZ9XbY6hrnGiUigV+5qB6ggS1v8Bz7UhlX3PCmdR7XaE9AgLvHC5UoyWoiAdjHRLi5/lVjPCtc3621AhAqaQ1Tr6PSjOyDg+dewRMOjVfTDTSlJLF4KS6QSOlFvUTOst+FtRn/nExBsHrFlM1KlmzeacPNXznZ+Ohj19RIR5P6xzcZjURXao/NVTi/+eKvT/ona5R1SeNJ/uHO4w9vehnKYneVn055wIynHwmIvh/MsCzVEhw=
  - secure: U/p49zNAF//CbF/0ReonT5iDDwcUkWiK+M39WDb+k91cdMwV0N+hI+KAFPts+kMB9dP+kqL3CPrDt1vDAoPYowubKgJGhFEPgo0C+taWLvC9ANBKBZcvGtX8hDWrLh4YbbhOQAkgKw3zhPqEuGAId2y9JgOWL5jxWRhVOoefainUZ5X1S0Gpcw1qKWOJCaoGAtVXJH/AxTi80P9Hu7tViJynKhgo++T69OMbhzrj3amugiosfW4m5xwHo2pxfA/RkkTXGEZRJV71kSuWDZenE86W7UEM7Go5tT/+RL1Ea9jyHj3Ezg9DyTcZILJFyrG4oQth53jBqO/nAZXBuY72N4MIFGzuF6ykwbFthVXsOJBI9dh/PIgoaAfiH5Lyk/dku9p3vofweE8YyWK410uksvKP7KlS3uu9XfO1MJC2x9ak1dASS5BA1KIQI9Favjs92pUw0+iWjgHaWClV3Oljv0OTUBxYwpUaxC4X84HrQIy3en2RMdTjZQ1OqhtGP3omS/RWyKR5SQhF4MaevN3QDyFL49C2pM42lkbS68fDdzCg/BQkIFPqpFEghtd0dYgRdvjbyB27ETdAJUse9r9zOSTvnX3i/N3oPv014N8+Amz6+/Ay1LJm0xOpoYl/05qjHrH+MaGsYMzdH8XxIZ0+HoUhutwxNE56fjeFnSRtG00=
  - secure: ISvmNHUjWiArohUfGey6MGrZMtFamriQ8ATH1Pq7GC+QHEfm+ztoOpLyTrs9BQmNHvjCVJSmpGdjdK00sdEtBI1vAEWwNpX7cXoOFvpp5prbK3C8ajJofCJibYGXJZKRF434bc3VzfMrzpxPjtdtsU3H155w6qsubYz+6kLhgSxNN3G72F9GeFexH/svvDfPQFbtVV+Ur8+EbcEblBP7LIVqcw59VYZoBQMGcNi/UTfQyJDmrokgi1J8J/1dh6G41id5yGesp+gG4DvjC90SPQyCv5kxjctksq37mig9z47IjNjsxg641+pyHTFx6L9F3hEEtq3adrPSGXEdugUxsYNThETB/9+Bh2vAFTiNdFRWny+EnIO11WpCxZbjkxYy66geKqJv2KS+hjmr0BXybE+R338tqHzAP5rVeueyP4djycXAuJw4zKFO/vJ8Ts0XGt85m2O6hTL/zM09EkiboFszZZX0WmazjCENz90nqeiFWPD/Lxcj9s5JnVGXkNeFWgHH23Rgb7DgorJLjoneivyIKxH6zqWGwAudkcnCHumRnkR+vjOBQS3SUFUquYCCDoL3VUFrRzGLmJKrEgBvmuH20nKnhUt1tpTLj8t+RCiu6+0Rb/yCX4CQgbfThnto0gdr9gVmVdNIHYDVWxy/9krnThYKfvNGDn6bjepVG6s=
addons:
  firefox: latest
  chrome: stable
sudo: required
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
